package parser

// Tags describe AST nodes, independently of lexical token numbers.
type Tag uint8

const (
	TagNone Tag = iota
	TagChunk
	TagBlock
	TagList
	TagPair
	TagIdentifier
	TagNamePath
	TagParameter
	TagVarargParameter
	TagImplicitSelf
	TagAttribute
	TagBinding
	TagEmpty
	TagAssignment
	TagLocalDeclaration
	TagGlobalDeclaration
	TagGlobalWildcardDeclaration
	TagFunctionDeclaration
	TagMethodDeclaration
	TagLocalFunctionDeclaration
	TagGlobalFunctionDeclaration
	TagCallStatement
	TagIf
	TagBranch
	TagWhile
	TagRepeatUntil
	TagNumericFor
	TagGenericFor
	TagDoBlock
	TagReturn
	TagBreak
	TagGoto
	TagLabel
	TagNameTarget
	TagFieldTarget
	TagIndexTarget
	TagNil
	TagBoolean
	TagInteger
	TagFloat
	TagString
	TagNameReference
	TagVararg
	TagTableConstructor
	TagFunctionExpression
	TagParenthesized
	TagFieldAccess
	TagIndexAccess
	TagCallExpression
	TagMethodCallExpression
	TagTableArgumentCall
	TagStringArgumentCall
	TagArrayField
	TagKeyField
	TagNameField
	TagNot
	TagNegate
	TagBitwiseNot
	TagLength
	TagOr
	TagAnd
	TagEqual
	TagNotEqual
	TagLess
	TagLessEqual
	TagGreater
	TagGreaterEqual
	TagBitOr
	TagBitXor
	TagBitAnd
	TagShiftLeft
	TagShiftRight
	TagConcat
	TagAdd
	TagSubtract
	TagMultiply
	TagModulo
	TagDivide
	TagIntegerDivide
	TagPower
)
